### ISSUE TITLE
[Feature]: Support topic segments as placeholders to reduce amount of configuration code

### ISSUE THREAD

**Issue by ova2** [solacecommunity/spring-cloud-stream-request-reply#4]
### Feature Description

Currently, I'm trying to load topology data from an external topology provider via request / reply. There are many entities like operating points, track edges, signals, main tracks, train number fields, etc. I load all of them in parallel. This works very well, but the configuration which is required for that is really huge. Configuration example for only two entities:

```yml
spring:
  cloud:
    function:
      definition: trackEdgeRequest;operatingPointRequest;...
    stream:
      requestreply:
        bindingMapping:
          - binding: trackEdgeRequest
            replyTopic: ${topo-data-provider.topic-prefix}/gleiskante/reply/${application.hostname}/${replyTopicWithWildcards|uuid}
            topicPatterns:
              - .*infrastructure/gleiskante/request
          - binding: operatingPointRequest
            replyTopic: ${topo-data-provider.topic-prefix}/betriebspunkt/reply/${application.hostname}/${replyTopicWithWildcards|uuid}
            topicPatterns:
              - .*infrastructure/betriebspunkt/request
            ...

      bindings:
        # bindings for requesting topo data
        trackEdgeRequest-out-0:
          contentType: application/x-protobuf
          binder: solace
        trackEdgeRequest-in-0:
          destination: ${replyTopicWithWildcards|trackEdgeRequest|*}
          contentType: application/x-protobuf
          binder: solace
        operatingPointRequest-out-0:
          contentType: application/x-protobuf
          binder: solace
        operatingPointRequest-in-0:
          destination: ${replyTopicWithWildcards|operatingPointRequest|*}
          contentType: application/x-protobuf
          binder: solace
       ...
```

In order to reduce this amount of code I propose to introduce a support of substitutable topic segments. For instance, if a topic segment begins with a colon `(:)`, then the segment acts as a placeholder for any segment value. Substituted segment values are available via the same syntax and the same segment names in `topicPatterns`. This is inspired by [SCION framework](https://scion-microfrontend-platform-developer-guide.vercel.app/) (more or less). An example of what I mean:

```yml
spring:
  cloud:
    function:
      definition: topoRequest;...
    stream:
      requestreply:
        bindingMapping:
          - binding: topoRequest
            replyTopic: ${topo-data-provider.topic-prefix}/:entity/reply/${application.hostname}/${replyTopicWithWildcards|uuid}
            topicPatterns:
              - .*infrastructure/:entity/request
            ...

      bindings:
        # bindings for requesting topo data
        topoRequest-out-0:
          contentType: application/x-protobuf
          binder: solace
        topoRequest-in-0:
          destination: ${replyTopicWithWildcards|topoRequest|*}
          contentType: application/x-protobuf
          binder: solace
       ...
```

So, as you see, there are only one "generic" configuration for all topology entities. It doesn't matter if we have 100 or 200 of them.

If you want, I can try to provide a PR. I think I understood how `RequestReplyServiceImpl` works. At first glance, we could implement this feature. Wdyt? Many thanks.

### Use Case

We need this feature with flexible topic definitions for writing less configuration in application yaml files.

### Proposed Solution

See above

**Comment by ova2** [comment]
Another syntax came in my mind. We can also use Java's Regex capturing groups. E.g. we could write a RegEx in `topicPatterns` and use numbers in `replyTopic` to reference matching groups (starting with 1). Example:

````yml
  replyTopic: ${someTopicPrefix}/{{1}}/{{2}}/reply/${replyTopicWithWildcards|uuid}
  topicPatterns:
    - .*infrastructure/(.*)/(\\d+)/request
```

Here, `{{1}}` references the values from the 1. match (`(.*)`) and `{{2}}` references the values from the 2. match (`(\\d+)`).
